# Generated by Django 4.2.8 on 2023-12-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tc',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
