# Generated by Django 4.2.3 on 2023-12-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_otp_alter_user_tc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
